market_analysis:
  data_dir:
    dev: .data
    prod: .data
  lookback_days: 100
  provider: yahoo
  tickers:
  - JPM
  - GOOGL
  - TSLA
  - AMZN
  - NVDA
  - META
  - MSFT
  - AAPL
  - V
  - AMD
output:
  file: positions.csv
tws:
  client_id: 1
  host: host.docker.internal
  password: ${TWS_PASSWORD}
  port: 7497
  user: rnbbop246
