version: "3.8"

services:
  market-scanner:
    build: .
    container_name: market-scanner
    restart: unless-stopped
    labels:
      - "traefik.enable=true"  # Enable Traefik routing for market-scanner
      # Basic router configuration
      - "traefik.http.routers.market-scanner.rule=PathPrefix(`/api`)"
      - "traefik.http.services.market-scanner.loadbalancer.server.port=8000"
      # Configure and attach the strip-prefix middleware
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.market-scanner.middlewares=strip-api-prefix@docker"
    environment:
      - ENV_MODE=prod
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./.data:/app/.data
      - ./config.yaml:/app/config.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trading-network

  # Traefik reverse proxy service
  reverse-proxy:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.insecure=true"      # Enable Traefik dashboard without auth (development only)
      - "--providers.docker=true"   # Enable Docker provider to detect services
      - "--providers.docker.exposedbydefault=false"  # Don't expose containers by default
      - "--entrypoints.web.address=:80"  # HTTP entrypoint
      - "--entrypoints.websecure.address=:443" # HTTPS entrypoint
     # Add debug logging
      - "--log.level=DEBUG"
    ports:
      - "80:80"      # HTTP
      - "443:443"  # HTTPS (for production)
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - trading-network

  # Test service to verify Traefik routing
  whoami:
    image: traefik/whoami  # Simple test container that shows request info
    container_name: whoami
    labels:
      - "traefik.enable=true"  # Enable Traefik for this container
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"  # Route requests for whoami.localhost
      - "traefik.http.services.whoami.loadbalancer.server.port=80"   # Container port to route to
    networks:
      - trading-network

# Shared network for all services
networks:
  trading-network:
    name: trading-network 