version: "3.8"

services:
  market-scanner:
    build: .
    container_name: market-scanner
    restart: unless-stopped
    environment:
      - ENV_MODE=prod
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./.data:/app/.data
    networks:
      - trading-network

networks:
  trading-network:
    name: trading-network 