   creation_rules:
     - path_regex: config/.*\.yml$
       pgp: >-
         $(cat /mnt/c/Users/qwek3/Workspace/IBKR/certs/sops.pub | base64 -w0)
       encrypted_regex: '^(api_key|password|token|secret|url|allowed_hosts|allowed_users)$'