market_analysis:
  data_dir: .data              # @env: DATA_DIR
  lookback_days: 100          # @min: 1 @max: 365
  provider: yahoo
  tickers:
    - JPM
    - GOOGL
    - TSLA
    - AMZN
    - NVDA
    - META
    - MSFT
    - AAPL
    - V
    - AMD

output:
  file: positions.csv          # @env: OUTPUT_FILE

tws:
  client_id: 1                # @env: TWS_CLIENT_ID
  host: host.docker.internal  # @env: TWS_HOST
  password: $TWS_PASSWORD     # Secret
  port: 7497                  # @env: TWS_PORT
  user: rnbbop246             # @env: TWS_USER

environments:
  development:
    domain: localhost
    port: 8000                # @env: DEV_PORT
    env_mode: dev
    log_level: debug          # @enum: debug,info,warning,error

  production:
    domain: $DOMAIN           # Secret
    port: 8000                # @env: PROD_PORT
    env_mode: prod
    log_level: info

bot_gateway:
  telegram:
    bot_token: $TELEGRAM_BOT_TOKEN       # Secret
    webhook_secret: $TELEGRAM_WEBHOOK_SECRET  # Secret
    allowed_users:
      - $TELEGRAM_ADMIN_ID               # Secret
    rate_limit:
      requests_per_minute: 60            # @min: 1

  security:
    api_key: $MARKET_API_KEY             # Secret
    tls_verify: true                     # @type: boolean
    allowed_hosts:
      - $DOMAIN                          # Secret