market_analysis:
  data_dir: .data
  lookback_days: 100
  provider: yahoo
  tickers:
  - JPM
  - GOOGL
  - TSLA
  - AMZN
  - NVDA
  - META
  - MSFT
  - AAPL
  - V
  - AMD
output:
  file: positions.csv
tws:
  client_id: 1
  host: host.docker.internal
  password: ${TWS_PASSWORD}
  port: 7497
  user: rnbbop246
bot_gateway:
  domain: localhost
  port: 8001
  env_mode: dev
  log_level: debug
  telegram:
    bot_token: ${TELEGRAM_BOT_TOKEN}
    webhook_secret: ${TELEGRAM_WEBHOOK_SECRET}
    allowed_users:
    - ${TELEGRAM_ADMIN_ID}
    rate_limit:
      requests_per_minute: 60
  security:
    api_key: ${MARKET_API_KEY}
    tls_verify: true
    allowed_hosts:
    - ${DOMAIN}
