name: Code Coverage

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - src/**
      - tests/**
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov httpx

      - name: Run tests with coverage
        id: coverage
        run: |
          pytest tests/ -v --cov=src \
          --cov-report=html \
          --cov-report=term-missing \
          | tee pytest_output.txt
          coverage=$(grep "TOTAL" pytest_output.txt | awk '{print $4}')
          echo "coverage_percentage=$coverage" >> $GITHUB_OUTPUT

      - name: Get Workflow Run URL
        id: workflow_url
        run: |
          WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "WORKFLOW_URL=$WORKFLOW_URL" >> $GITHUB_ENV
          echo "Workflow Run URL: $WORKFLOW_URL"

      - name: Generate Coverage Badge URL
        run: |
          COVERAGE=$(echo ${{ steps.coverage.outputs.coverage_percentage }} | sed 's/%//')
          COLOR=$(awk -v coverage=$COVERAGE 'BEGIN {
            if (coverage < 50) print "red";
            else if (coverage < 80) print "yellow";
            else print "brightgreen";
          }')
          # URL encode the workflow URL
          ENCODED_URL=$(echo "${{ env.WORKFLOW_URL }}" | sed 's/\//%2F/g' | sed 's/:/%3A/g')
          # Create badge URL with encoded link
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}?link=${ENCODED_URL}"
          echo "BADGE_URL=$BADGE_URL" >> $GITHUB_ENV

      - name: Download Badge as SVG
        run: |
          mkdir -p .github/badges
          curl -L -o .github/badges/code_coverage.svg "$BADGE_URL"

      - name: Commit Badge to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create directory if it doesn't exist
          mkdir -p .github/badges
          
          # Add and commit only the badge file
          git add .github/badges/code_coverage.svg
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update code coverage badge"
            git push
          fi