name: Code Coverage

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - src/**
      - tests/**
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov httpx

      - name: Run tests with coverage
        id: coverage
        run: |
          pytest tests/ -v --cov=src \
          --cov-report=html \
          --cov-report=term-missing \
          | tee pytest_output.txt
          coverage=$(grep "TOTAL" pytest_output.txt | awk '{print $4}')
          echo "coverage_percentage=$coverage" >> $GITHUB_OUTPUT

      - name: Generate Coverage Badge URL
        run: |
          COVERAGE=${{ steps.coverage.outputs.coverage_percentage }}
          COLOR=$(awk -v coverage=$COVERAGE 'BEGIN {
            if (coverage < 50) print "red";
            else if (coverage < 80) print "yellow";
            else print "brightgreen";
          }')
          BADGE_URL="https://img.shields.io/badge/Code_Coverage-$COVERAGE%25-$COLOR.svg?logo=github"
          echo "BADGE_URL=$BADGE_URL" >> $GITHUB_ENV

      - name: Download Badge as SVG
        run: |
          mkdir -p .github/badges
          curl -o .github/badges/code_coverage.svg "$BADGE_URL"

      - name: Commit Badge to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add .github/badges/code_coverage.svg
          git commit -m "Update badge in .github/badges folder"
          git push https://${{ secrets.PAT }}@github.com/MoiKeyboard/moi-bkr.git HEAD:main
        env:
          PAT: ${{ secrets.PAT }}